on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  nix_flake_check:
    runs-on: my-ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install nix
        uses: https://github.com/cachix/install-nix-action@v27
      - name: Run `nix flake check` to run formatters, linters, and tests
        run: nix flake check --print-build-logs
